nome = str(input('Qual o nome que deseja analisar? '))
maiu = nome.upper()
print('O nome analisado, todo em maiusculo, fica: \n{}'.format(maiu))
minu = nome.lower()
print('Com todas as letras minusculas, fica: \n{}'.format(minu))
div = nome.split()
juntar = ''.join(div)
total = len(juntar)
totalprimeira = len(div[0])
print('O número total de caracteres é: \n{}'.format(total))
print('O total de caracteres apenas da primeira palavra é: \n{}'.format(totalprimeira))
